name: Deploy

on:
  push:
    branches:
      - main

env:
  DOMAIN: "oidc.signinwithethereum.org"

jobs:
  deploy-page:
    runs-on: ubuntu-latest
    name: Deploy Page
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Frontend
        run: |
          cd siwe-oidc/js/ui
          npm install
          npm run build
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - name: Publish Page
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: siwe-oidc
          command: pages publish --project-name=ens-oidc static --commit-dirty=true --branch=main

  deploy-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./siwe-oidc
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install wrangler
        run: |
          cargo install wrangler
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Publish Worker
        run: |
          cp wrangler_example.toml wrangler.toml
          sed -i '1s/^/routes = ["'$DOMAIN'\/.w*", "'$DOMAIN'\/j*", "'$DOMAIN'\/t*", "'$DOMAIN'\/a*", "'$DOMAIN'\/r*", "'$DOMAIN'\/u*", "'$DOMAIN'\/s*", "'$DOMAIN'\/c*"]\n/' wrangler.toml
          sed -i 's/id = \"\", preview_id = \"\"/id = \"${{ secrets.KV_ID }}\", preview_id = \"${{ secrets.KV_ID }}\"/g' wrangler.toml
          sed -i 's/BASE_URL = .*/BASE_URL = "https:\/\/'$DOMAIN'"/g' wrangler.toml
          sed -i 's/^.*ETH_PROVIDER = .*/ETH_PROVIDER = \"https:\/\/cloudflare-eth.com\"/g' wrangler.toml
          wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
